#!/bin/bash
# qnli
# nohup bash glue_script/script_qnli.sh &
# QNLI
nohup bash -c 'CUDA_VISIBLE_DEVICES=1 python run_glue_MPO_losslayer.py --model_name_or_path /mnt/zhanyuliang/data/nlp_data/theseus/BertFineTrain/download/qnli/bert-base-uncased-qnli/ --task_name qnli --do_train --do_eval --do_lower_case --data_dir /mnt/zhanyuliang/data/nlp_data/GLUE/QNLI --max_seq_length 128 --per_gpu_train_batch_size 32 --per_gpu_eval_batch_size 32 --learning_rate 5e-6 --save_steps 100 --num_train_epochs 3 --output_dir /mnt/zhanyuliang/data/checkpoint/nlp/theseus/save_successor/ --evaluate_during_training --replacing_rate 0.3 --scheduler_type linear --scheduler_linear_k 0.0001 --overwrite_output_dir' >log/qnli_mpo.log >&1 &
wait
nohup bash -c 'CUDA_VISIBLE_DEVICES=1 python run_glue_MPO_losslayer.py --model_name_or_path /mnt/zhanyuliang/data/nlp_data/theseus/BertFineTrain/download/qnli/bert-base-uncased-qnli/ --task_name qnli --do_train --do_eval --do_lower_case --data_dir /mnt/zhanyuliang/data/nlp_data/GLUE/QNLI --max_seq_length 128 --per_gpu_train_batch_size 32 --per_gpu_eval_batch_size 32 --learning_rate 5e-6 --save_steps 100 --num_train_epochs 3 --output_dir /mnt/zhanyuliang/data/checkpoint/nlp/theseus/save_successor/ --evaluate_during_training --replacing_rate 0.3 --scheduler_type linear --scheduler_linear_k 0.0003 --overwrite_output_dir' >log/qnli_mpo_2.log >&1 &
wait
nohup bash -c 'CUDA_VISIBLE_DEVICES=1 python run_glue_MPO_losslayer.py --model_name_or_path /mnt/zhanyuliang/data/nlp_data/theseus/BertFineTrain/download/qnli/bert-base-uncased-qnli/ --task_name qnli --do_train --do_eval --do_lower_case --data_dir /mnt/zhanyuliang/data/nlp_data/GLUE/QNLI --max_seq_length 128 --per_gpu_train_batch_size 32 --per_gpu_eval_batch_size 32 --learning_rate 5e-6 --save_steps 100 --num_train_epochs 3 --output_dir /mnt/zhanyuliang/data/checkpoint/nlp/theseus/save_successor/ --evaluate_during_training --replacing_rate 0.3 --scheduler_type linear --scheduler_linear_k 0.0006 --overwrite_output_dir' >log/qnli_mpo_3.log >&1 &
wait